import path from 'path';
import { Logger } from '../utils/logger';
import { FileHelpers } from '../utils/file-helpers';
import { DetectedFeature } from '../analyzer/project-detector';
import { AnalyzedFeature } from '../analyzer/codebase-ai-analyzer';

export interface TestGenerationOptions {
  outputDir: string;
  baseUrl?: string;
  author?: string;
}

export interface GeneratedTest {
  fileName: string;
  filePath: string;
  content: string;
  feature: DetectedFeature | AnalyzedFeature;
}

export interface TestGenerationCallbacks {
  onTestGenerated?: (fileName: string, index: number, total: number) => void;
  onError?: (featureName: string, error: unknown) => void;
}

export class TestBatchGenerator {
  private logger: Logger;
  private callbacks: TestGenerationCallbacks;

  constructor(logger?: Logger, callbacks?: TestGenerationCallbacks) {
    this.logger = logger || new Logger();
    this.callbacks = callbacks || {};
  }

  async generateTests(
    features: DetectedFeature[],
    options: TestGenerationOptions
  ): Promise<GeneratedTest[]> {
    const generatedTests: GeneratedTest[] = [];

    await FileHelpers.ensureDirectory(options.outputDir);

    for (let i = 0; i < features.length; i++) {
      const feature = features[i];
      try {
        const test = await this.generateTest(feature, options);
        generatedTests.push(test);
        this.callbacks.onTestGenerated?.(test.fileName, i + 1, features.length);
      } catch (error) {
        this.logger.error(`Failed to generate test for ${feature.name}: ${error}`);
        this.callbacks.onError?.(feature.name, error);
      }
    }

    return generatedTests;
  }

  async generateTestsFromAI(
    features: AnalyzedFeature[],
    options: TestGenerationOptions
  ): Promise<GeneratedTest[]> {
    const generatedTests: GeneratedTest[] = [];

    await FileHelpers.ensureDirectory(options.outputDir);

    for (let i = 0; i < features.length; i++) {
      const feature = features[i];
      try {
        const test = await this.generateTestFromAI(feature, options);
        generatedTests.push(test);
        this.callbacks.onTestGenerated?.(test.fileName, i + 1, features.length);
      } catch (error) {
        this.logger.error(`Failed to generate test for ${feature.name}: ${error}`);
        this.callbacks.onError?.(feature.name, error);
      }
    }

    return generatedTests;
  }

  private async generateTest(
    feature: DetectedFeature,
    options: TestGenerationOptions
  ): Promise<GeneratedTest> {
    const sanitizedFeatureName = feature.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');

    const fileName = `${sanitizedFeatureName}-test.md`;
    const filePath = path.join(options.outputDir, fileName);

    const content = this.generateMarkdown(feature, options);

    await FileHelpers.writeFile(filePath, content);

    return {
      fileName,
      filePath,
      content,
      feature
    };
  }

  private async generateTestFromAI(
    feature: AnalyzedFeature,
    options: TestGenerationOptions
  ): Promise<GeneratedTest> {
    const sanitizedFeatureName = feature.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');

    const fileName = `${sanitizedFeatureName}-test.md`;
    const filePath = path.join(options.outputDir, fileName);

    const content = this.generateMarkdownFromAI(feature, options);

    await FileHelpers.writeFile(filePath, content);

    return {
      fileName,
      filePath,
      content,
      feature
    };
  }

  private generateMarkdown(feature: DetectedFeature, options: TestGenerationOptions): string {
    const lines: string[] = [];

    lines.push(`# Test: ${feature.name}`);
    lines.push('');

    lines.push('## Metadata');
    lines.push('Version: 0.2.0');
    lines.push(`Author: ${options.author || 'Generated by zimpleQA'}`);
    lines.push(`Priority: ${feature.priority}`);
    lines.push(`Tags: ${feature.type}, auto-generated, manual`);
    lines.push('');

    lines.push('## Description');
    if (feature.description) {
      lines.push(feature.description);
    } else {
      lines.push(`Test the ${feature.name.toLowerCase()} functionality of the application.`);
    }
    lines.push('');

    lines.push('## URL');
    if (feature.routes.length > 0) {
      const primaryRoute = feature.routes[0];
      if (options.baseUrl) {
        lines.push(`${options.baseUrl}${primaryRoute}`);
      } else {
        lines.push(`\${BASE_URL}${primaryRoute}`);
      }
    } else {
      lines.push(options.baseUrl || '${BASE_URL}');
    }
    lines.push('');

    lines.push('## Preconditions');
    lines.push('- Application is running and accessible');
    if (feature.type === 'auth') {
      lines.push('- User account exists for testing');
      lines.push('- Valid credentials are available');
    }
    if (feature.type === 'payment' || feature.type === 'checkout') {
      lines.push('- Test payment method is available');
      lines.push('- Products/items are available in the system');
    }
    lines.push('');

    lines.push('## Steps');
    const steps = this.generateSteps(feature);
    steps.forEach((step, index) => {
      lines.push(`${index + 1}. ${step}`);
    });
    lines.push('');

    lines.push('## Expected Results');
    const expectedResults = this.generateExpectedResults(feature);
    expectedResults.forEach(result => {
      lines.push(`- ${result}`);
    });
    lines.push('');

    lines.push('## Postconditions');
    const postconditions = this.generatePostconditions(feature);
    postconditions.forEach(pc => {
      lines.push(`- ${pc}`);
    });
    lines.push('');

    lines.push('## Notes');
    lines.push(`- Feature type: ${feature.type}`);
    lines.push(`- Confidence: ${Math.round(feature.confidence * 100)}%`);
    if (feature.components.length > 0) {
      lines.push(`- Related components: ${feature.components.join(', ')}`);
    }
    lines.push('- This test was auto-generated. Review and adjust as needed.');
    lines.push('');

    if (!options.baseUrl) {
      lines.push('## Variables');
      lines.push('BASE_URL=http://localhost:3000');
    }

    return lines.join('\n');
  }

  private generateMarkdownFromAI(feature: AnalyzedFeature, options: TestGenerationOptions): string {
    const lines: string[] = [];

    lines.push(`# Test: ${feature.name}`);
    lines.push('');

    lines.push('## Metadata');
    lines.push('Version: 0.2.0');
    lines.push(`Author: ${options.author || 'Generated by zimpleQA'}`);
    lines.push(`Priority: ${feature.priority}`);
    lines.push(`Tags: ${feature.type}, auto-generated, manual, ai-analyzed`);
    lines.push('');

    lines.push('## Description');
    lines.push(feature.description || `Test the ${feature.name.toLowerCase()} functionality of the application.`);
    lines.push('');

    lines.push('## URL');
    if (feature.routes.length > 0) {
      const primaryRoute = feature.routes[0];
      if (options.baseUrl) {
        lines.push(`${options.baseUrl}${primaryRoute}`);
      } else {
        lines.push(`\${BASE_URL}${primaryRoute}`);
      }
    } else {
      lines.push(options.baseUrl || '${BASE_URL}');
    }
    lines.push('');

    lines.push('## Preconditions');
    lines.push('- Application is running and accessible');
    lines.push('- User has appropriate permissions');
    
    if (feature.type === 'auth') {
      lines.push('- User account exists for testing');
      lines.push('- Valid credentials are available');
    }
    if (feature.type === 'payment' || feature.type === 'checkout') {
      lines.push('- Test payment method is available');
      lines.push('- Products/items are available in the system');
    }
    if (feature.type === 'crud') {
      lines.push('- Test data is available or can be created');
    }
    lines.push('');

    lines.push('## Steps');
    if (feature.suggestedTests && feature.suggestedTests.length > 0) {
      feature.suggestedTests.forEach((test, index) => {
        lines.push(`${index + 1}. ${test}`);
      });
    } else {
      const defaultSteps = this.generateStepsFromAI(feature);
      defaultSteps.forEach((step, index) => {
        lines.push(`${index + 1}. ${step}`);
      });
    }
    lines.push('');

    lines.push('## Expected Results');
    const expectedResults = this.generateExpectedResultsFromAI(feature);
    expectedResults.forEach(result => {
      lines.push(`- ${result}`);
    });
    lines.push('');

    lines.push('## Postconditions');
    lines.push('- Test data is cleaned up if necessary');
    if (feature.type === 'auth') {
      lines.push('- User is logged out');
    }
    if (feature.type === 'payment' || feature.type === 'checkout') {
      lines.push('- Test transactions are cancelled/refunded');
    }
    lines.push('');

    lines.push('## Notes');
    lines.push(`- Feature type: ${feature.type}`);
    lines.push(`- Confidence: ${Math.round(feature.confidence * 100)}%`);
    if (feature.components.length > 0) {
      lines.push(`- Related components: ${feature.components.join(', ')}`);
    }
    if (feature.routes.length > 0) {
      lines.push(`- Related routes: ${feature.routes.join(', ')}`);
    }
    lines.push('- This test was auto-generated by AI. Review and adjust as needed.');
    lines.push('');

    if (!options.baseUrl) {
      lines.push('## Variables');
      lines.push('BASE_URL=http://localhost:3000');
    }

    return lines.join('\n');
  }

  private generateSteps(feature: DetectedFeature | AnalyzedFeature): string[] {
    const steps: string[] = [];
    const route = feature.routes.length > 0 ? feature.routes[0] : '/';
    const type = feature.type as string;

    switch (type) {
      case 'auth':
        steps.push(`Navigate to ${route}`);
        steps.push('Verify the page loads correctly');
        steps.push('Locate the login/register form');
        steps.push('Enter valid credentials');
        steps.push('Submit the form');
        steps.push('Wait for authentication response');
        steps.push('Verify successful authentication');
        break;

      case 'payment':
        steps.push(`Navigate to ${route || '/checkout'}`);
        steps.push('Verify payment page loads');
        steps.push('Enter payment details');
        steps.push('Verify payment information is validated');
        steps.push('Submit payment');
        steps.push('Wait for payment confirmation');
        steps.push('Verify payment success message');
        break;

      case 'checkout':
        steps.push(`Navigate to ${route || '/cart'}`);
        steps.push('Verify cart items are displayed');
        steps.push('Proceed to checkout');
        steps.push('Enter shipping information');
        steps.push('Select shipping method');
        steps.push('Review order summary');
        steps.push('Confirm order');
        break;

      case 'form':
        steps.push(`Navigate to ${route}`);
        steps.push('Verify form is displayed');
        steps.push('Fill in all required fields');
        steps.push('Verify field validation works');
        steps.push('Submit the form');
        steps.push('Verify form submission response');
        break;

      default:
        steps.push(`Navigate to ${route}`);
        steps.push('Verify the page loads correctly');
        steps.push('Test main functionality');
        steps.push('Verify expected behavior');
    }

    return steps;
  }

  private generateStepsFromAI(feature: AnalyzedFeature): string[] {
    const steps: string[] = [];
    const route = feature.routes.length > 0 ? feature.routes[0] : '/';

    steps.push(`Navigate to ${route}`);
    steps.push('Wait for page to load completely');
    
    if (feature.type === 'auth') {
      steps.push('Locate authentication form');
      steps.push('Enter test credentials');
      steps.push('Submit authentication request');
      steps.push('Verify successful login/registration');
    } else if (feature.type === 'payment' || feature.type === 'checkout') {
      steps.push('Review cart/order items');
      steps.push('Enter payment information');
      steps.push('Confirm payment');
      steps.push('Verify transaction success');
    } else if (feature.type === 'form') {
      steps.push('Fill in required form fields');
      steps.push('Submit the form');
      steps.push('Verify submission success');
    } else if (feature.type === 'crud') {
      steps.push('Test create operation');
      steps.push('Test read operation');
      steps.push('Test update operation');
      steps.push('Test delete operation');
    } else {
      steps.push('Interact with main elements');
      steps.push('Verify expected behavior');
    }

    steps.push('Verify no errors are displayed');

    return steps;
  }

  private generateExpectedResults(feature: DetectedFeature | AnalyzedFeature): string[] {
    const results: string[] = [];
    const type = feature.type as string;

    switch (type) {
      case 'auth':
        results.push('User is successfully authenticated');
        results.push('Session is created');
        results.push('User is redirected to appropriate page');
        results.push('No error messages displayed');
        break;

      case 'payment':
        results.push('Payment is processed successfully');
        results.push('Confirmation message is displayed');
        results.push('Transaction is recorded');
        break;

      case 'checkout':
        results.push('Order is created successfully');
        results.push('Order confirmation is displayed');
        results.push('User receives order confirmation');
        break;

      case 'form':
        results.push('Form is submitted successfully');
        results.push('Success message displayed');
        results.push('Data is saved correctly');
        break;

      default:
        results.push('Feature works as expected');
        results.push('No errors displayed');
    }

    return results;
  }

  private generateExpectedResultsFromAI(feature: AnalyzedFeature): string[] {
    const results: string[] = [];
    const type = feature.type;

    if (type === 'auth') {
      results.push('User authentication completes successfully');
      results.push('User session is established');
      results.push('User is redirected to the correct page');
    } else if (type === 'payment' || type === 'checkout') {
      results.push('Payment is processed without errors');
      results.push('Order confirmation is received');
      results.push('Transaction is recorded in the system');
    } else if (type === 'form') {
      results.push('Form validation works correctly');
      results.push('Form submission is successful');
      results.push('Data is persisted correctly');
    } else if (type === 'crud') {
      results.push('All CRUD operations complete successfully');
      results.push('Data integrity is maintained');
    } else if (type === 'search') {
      results.push('Search results are relevant');
      results.push('Search performance is acceptable');
    } else {
      results.push('Feature works as expected');
      results.push('No errors or warnings displayed');
      results.push('User experience is smooth');
    }

    results.push('No unexpected errors in console');

    return results;
  }

  private generatePostconditions(feature: DetectedFeature | AnalyzedFeature): string[] {
    const postconditions: string[] = [];
    const type = feature.type as string;

    postconditions.push('Test data is cleaned up if necessary');

    if (type === 'auth') {
      postconditions.push('User is logged out if needed');
      postconditions.push('Test session is terminated');
    }

    if (type === 'payment' || type === 'checkout') {
      postconditions.push('Test order is cancelled or marked as test');
      postconditions.push('Payment is refunded if real payment was made');
    }

    if (type === 'crud') {
      postconditions.push('Test items created are deleted');
      postconditions.push('Database state is restored');
    }

    return postconditions;
  }
}
